name: OpenHands Resolver

on:
  issues:
    types: [labeled, opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [labeled, opened]
  pull_request_review_comment:
    types: [created]

jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - uses: all-hands-ai/openhands-resolver@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.OPENAI_API_KEY }}
